### ISSUE TITLE
Collaborate on Centrifuge library changes

### ISSUE THREAD

**Issue by FZambia** [ryantxu/grafana-notes-panel#1]
@ryantxu hi:) First of all, sorry for the opening an absolutely irrelevant issue here. I tried to find your email address but failed with this. And none of the possible issue types in Grafana main repo suited well for this question.

I am the author of `github.com/centrifugal/centrifuge` library. I noticed that you were one who last committed to https://github.com/grafana/grafana/blob/master/pkg/services/live/live.go.

Centrifuge library has a v1.0.0 milestone and I am still making breaking changes in the library. I am glad you are using Centrifuge in Grafana – it's an honor actually, so I want to make sure my changes are OK with your use case.

All breaking changes I do in the library always allow implementing the same functionality as before since I can not break [Centrifugo](https://github.com/centrifugal/centrifugo) server compatibility (another service which depends on Centrifuge library which has a stable v2 release). But maybe these changes do not fit well into your design – then I suppose we can collaborate somehow to resolve possible issues before a new Centrifuge release.

If you are interested – I need to contact you somehow :) Maybe you don't want to post contacts here - then my email written in [my GitHub profile](https://github.com/FZambia).

**Comment by ryantxu** [comment]
Ha -- absolutely.  Working with Centrifuge has been great, I am totally impressed and would love to work with you to make sure we use it well.  I am particularly interested in https://github.com/centrifugal/centrifuge/issues/161 -- that could potentially simplify plans for how to expose streams to plugins
